### ISSUE TITLE
echo / monitor causes delay with warning messages

### ISSUE THREAD

**Issue by relffok** [ros2/geometry2#240] opened 2020-02-21 02:50 UTC
## Bug report

**Required Info:**

- Operating System:
Ubuntu 18.04
- Installation type:
Binaries & source
- Version or commit hash:
c95466b

#### Steps to reproduce issue

Publish static transformation 
```
ros2 run tf2_ros static_transform_publisher 0 0 1 0 0 0 1 foo bar
```

1) start ` tf2_monitor` 
```
ros2 run tf2_ros tf2_monitor
```
or 

2) start ` tf2_monitor` 
```
ros2 run tf2_ros tf2_monitor foo bar
```

or 

3) echo transform with` tf2_echo` 
```
ros2 run tf2_ros tf2_echo foo bar
```

#### Expected behavior
Transforms are shown after a short delay

#### Actual behavior
1) No output for a while (in my case 15 sec), then the expected output appears
2) Output:
`Waiting for transform chain to become available between foo and bar`

and several error messages of the following: 

`Warning: Invalid frame ID "foo" passed to canTransform argument target_frame - frame does not exist`

followed by a delay and the actual expected output. 

3) Several Error messages of the following: 

`Warning: Invalid frame ID "foo" passed to canTransform argument target_frame - frame does not exist`

followed by a delay and the actual expected output.

**Comment by sloretz** [comment] 2020-04-21 00:20
Thanks for the report @relffok !

It doesn't look like the transform data is delayed by `tf2_monitor`; instead the program is intentionally gathering messages for 10 seconds so it can report statistics on it. I was not able to reproduce a delay in `tf_echo`, though it does output a lot of useless warning messages. Both issues should be resolved by #254 which improves the console output of these tools.

**Closed as completed** 2020-04-21 18:43 UTC
Labels: bug
